version: 2.1
workflows:
  build:
    jobs:
      - build:
          filters:
            branches:
              only: master
jobs:
  build:
    working_directory: ~/websocket-line-order
    docker:
      - image: cimg/node:19.3.0
    steps:
      - checkout
      - run:
          name: Install Docker Compose
          command: |
            sudo curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
      - run: node --version
      - run: bash ./local/localdb.sh
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn lint
      - run: yarn test
      - run: yarn build
      - run: yarn start
